name: CI/CD Project
on:
  push:
    branches: [main]

jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v2

#     # - name: Build the docker
#     #   run: docker build -t cicd .

  Deploy:
#     needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Deploy in EC2
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY  }}
          HOST: ${{ secrets.HOST  }}
          USER_NAME: ${{ secrets.USER_NAME }}
          PORT: ${{ secrets.PORT }}

        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOST} -p ${PORT} '
           hostname '
            
